In [2]:
import numpy as np

In [4]:
Y1 = np.random.random((32, 2))

In [5]:
Y2 = np.random.random((32, 2))

In [6]:
Ws = np.random.random((64, 4))

In [7]:
X_fr = np.hstack((Y1, Y2))

In [8]:
X_fr.shape

(32, 4)

In [9]:
X = np.vstack((X_fr, Ws))

In [10]:
X.shape

(96, 4)

In [17]:
H = np.hstack((np.identity(32), np.zeros((32, 64))))

In [18]:
H.shape

(32, 96)

In [19]:
G_t = [[1, 0, 1, 0], [0,1,0,1]]

In [22]:
G_t = np.array(G_t).T

In [23]:
G_t

array([[1, 0],
       [0, 1],
       [1, 0],
       [0, 1]])

In [21]:
G_t.shape

(2, 4)

In [24]:
product = H@X@G_t

In [25]:
product.shape

(32, 2)

In [28]:
X[0,:]

array([0.92037318, 0.81566868, 0.72609856, 0.24610441])

In [29]:
X[0,0] + X[0,2]

1.646471740834253

In [30]:
X[0,1] + X[0,3]

1.0617730930988587

In [31]:
# product

In [34]:
vec_product = product.T.ravel()

In [36]:
rhs= np.kron(G_t.T, H)@(X.T.ravel())

In [37]:
vec_product == rhs

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])